import mongoose, { Schema } from "mongoose"
import bcrypt from "bcrypt"
import jwt from "jsonwebtoken"
import crypto from "crypto"

// Schema is a method which takes an object in which you define all the fields such as username, email, pass..
// the first object is all the fields and second object is the time stamps
const userschema = new Schema(
    {
        avatar: {
            // images are stored in the form of URL and URL is of type string
            type: {
                url: String,
                localpath: String //path of the file where the url is stored
            },
            // if user is not prviding any image to display, we can give him an default image
            default: {
                // using a placeholder service, search "placehold.co" on browser
                url: `https://placehold.co/200x200`,
                localpath: "" //this will be empty as we are not storing anything
            }
        },
        username: {
            type: String,
            //mongoDB will automatically make this field required, you don't have to write any extra logic
            required: true,
            unique: true, // mongoose will check into mongoDB for the uniqueness
            lowercase: true,
            trim: true, // all the additional spaces before and after are gone
            index: true // indexing so that it is easy for searching
        },
        email : {
            type: String,
            required: true,
            unique: true,
            trim: true
        },
        fullname: {
            type: String,
            trim: true
        },
        password: {
            // as nobody wants to save clear text passwords, so we will use a method to hash the passwords
            type: String,
            required: [true, "Password is required!"], // creating custom error if password is not empty
        },
        isemailverified: {
            type: Boolean,
            default: false
        },
        //using a JWT token system and for this we need to keep one token within our database
        refreshToken: {
            type: String,
        },
        forgotpasswordtoken: {
            type: String // a long string which has a token in it
        },
        // the forgotpasswordtoken cannot be kept all the time in the database, so we need an expiry of it
        forgotpasswordtokenexpiry: {
            type: Date //having expiry of some date
        },
        emailverificationtoken: {
            type: String
        },
        emailverificationtokenexpiry: {
            type: Date
        }
    },
    // two time stamps created-at and updated-at are made available to you
    {
        timestamps: true,

    }
)

// pre and post hooks can be attached to may things, we are attaching a pre hook to the "save" operation
userschema.pre("save", async function (next){
    // "isModified" checks what are the fields that are modified in this particular save operation
    if(!this.isModified("password")) return next() 
    //if password isn't modified the below function will do nothing
    // for "hashing" you need to provide two things - 
    //     1. the data you want to hash
    //     2. and how many rounds of hashing algo you want to apply
    // storing the hashed password into a variable (overwriting the password variable)
    this.password = await bcrypt.hash(this.password, 10)
    next()
})

userschema.methods.isPasswordCorrect = async function (password) {
    // telling bcrypt to comapare the current password with the stored password in the database
    return await bcrypt.compare(password, this.password) // it returns true or false
}

// method for generating "access" token
userschema.methods.generateAccesstoken = function() {
    // use "jwt" and create "signed" tokens
    // sign method takes parameters as objects
    // using return means whoever uses this method, gets back a token
    return jwt.sign(
        // the first information (1st object) is known as "payload"
        { // storing ids, emails etc
        _id: this._id, // this "_id" is automatically generated by mongoDB
        email: this.email,
        username: this.username,
        },

        // providing secret (without providing on our own it'll use the default one, but it is not that good)
        // the secret is saved in "env"
        process.env.ACCESS_TOKEN_SECRET,

        //providing expiry time
        {expiresIn: process.env.ACCESS_TOKEN_EXPIRY}
    )
}

// method for generating "refresh" token
userschema.methods.generateRefreshtoken = function() {
    // use "jwt" and create "signed" tokens
    // sign method takes parameters as objects
    // using return means whoever uses this method, gets back a token
    return jwt.sign(
        // the first information (1st object) is known as "payload"
        // the refresh token has less information than access token
        {
        _id: this._id, // this "_id" is automatically generated by mongoDB
        },

        // providing secret (without providing on our own it'll use the default one, but it is not that good)
        // the secret is saved in "env"
        process.env.REFRESH_TOKEN_SECRET,

        //providing expiry time
        {expiresIn: process.env.REFRESH_TOKEN_EXPIRY}
    )
}

// creating a without-data token
userschema.methods.generateTemporarytoken = function() {
    // generating 20 random bytes and converting it into string
    // crypto generates it in a hex value
    // this is an unhashed token, we will store this token in database so create an hashed version of it
    const unHashedtoken = crypto.randomBytes(20).toString("hex")

    const hashedtoken = crypto
        // using "sha256" algo to create hash
        .createHash("sha256")
        // using "update" method to convert unhashed into hashed
        .update("unHashedtoken")
        .digest("hex")

    // giving 20 mins of expiry time
    const tokenexpiry = Date.now() + (20*60*1000)

    // returning all these values
    return {unHashedtoken, hashedtoken, tokenexpiry}
}

// the schema that we want to use to create "User" schema is "userschema"
export const User = mongoose.model("User", userschema)